import * as cornerstone from '@cornerstonejs/core';
import * as cornerstoneTools from '@cornerstonejs/tools';
import dicomImageLoader from '@cornerstonejs/dicom-image-loader';
import dicomParser from 'dicom-parser';
import './style.css';
const {RenderingEngine,Enums}=cornerstone;
const {MouseBindings,ToolGroupManager,StackScrollMouseWheelTool,PanTool,ZoomTool,WindowLevelTool,addTool}=cornerstoneTools;
const state={files:[],imageIds:[],imageMeta:[],currentIndex:0,renderingEngine:null,viewport:null,cineTimer:null,cinePlaying:false,originalVOI:null,initialized:false};
const $=id=>document.getElementById(id);
const el={viewport:$('viewport'),fileInput:$('fileInput'),folderInput:$('folderInput'),openFilesBtn:$('openFilesBtn'),openFolderBtn:$('openFolderBtn'),dropOverlay:$('dropOverlay'),patientName:$('patientName'),patientId:$('patientId'),studyDescription:$('studyDescription'),modality:$('modality'),studyDate:$('studyDate'),seriesList:$('seriesList'),imageCountBadge:$('imageCountBadge'),statusText:$('statusText'),fileInfo:$('fileInfo'),hudPatient:$('hudPatient'),hudStudy:$('hudStudy'),hudModality:$('hudModality'),hudSlice:$('hudSlice'),windowText:$('windowText'),zoomText:$('zoomText'),sliceSlider:$('sliceSlider'),sliceLabel:$('sliceLabel'),prevBtn:$('prevBtn'),nextBtn:$('nextBtn'),cineBtn:$('cineBtn'),loading:$('loading'),loadingText:$('loadingText')};
const VIEWPORT_ID='DICOM_VIEWPORT',RENDERING_ENGINE_ID='DICOM_RENDERING_ENGINE';
const clean=v=>v==null||v===''?'—':String(v).replaceAll('^',' ').trim()||'—';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function loading(show,text){el.loading.classList.toggle('hidden',!show);el.loadingText.textContent=text||'Cargando DICOM…'}
function parseBasic(file,buffer){try{const d=dicomParser.parseDicom(new Uint8Array(buffer));const g=t=>{try{return d.string(t)||''}catch{return''}};return{patientName:clean(g('x00100010')),patientId:clean(g('x00100020')),studyDescription:clean(g('x00081030')),modality:clean(g('x00080060')),studyDate:clean(g('x00080020')),seriesDescription:clean(g('x0008103e')),instanceNumber:Number(g('x00200013'))||0,seriesInstanceUID:g('x0020000e'),fileName:file.name}}catch{return{patientName:'—',patientId:'—',studyDescription:'—',modality:'—',studyDate:'—',seriesDescription:'—',instanceNumber:0,fileName:file.name}}}
async function init(){if(state.initialized)return;await cornerstone.init();cornerstoneTools.init();dicomImageLoader.external.cornerstone=cornerstone;dicomImageLoader.external.dicomParser=dicomParser;dicomImageLoader.init({maxWebWorkers:Math.max(1,Math.min(4,navigator.hardwareConcurrency||2)),strict:false});addTool(WindowLevelTool);addTool(PanTool);addTool(ZoomTool);addTool(StackScrollMouseWheelTool);state.renderingEngine=new RenderingEngine(RENDERING_ENGINE_ID);state.renderingEngine.enableElement({viewportId:VIEWPORT_ID,type:Enums.ViewportType.STACK,element:el.viewport,defaultOptions:{background:[0,0,0]}});state.viewport=state.renderingEngine.getViewport(VIEWPORT_ID);const tg=ToolGroupManager.createToolGroup('DICOM_TOOL_GROUP');tg.addTool(WindowLevelTool.toolName);tg.addTool(PanTool.toolName);tg.addTool(ZoomTool.toolName);tg.addTool(StackScrollMouseWheelTool.toolName);tg.addViewport(VIEWPORT_ID,RENDERING_ENGINE_ID);tg.setToolActive(WindowLevelTool.toolName,{bindings:[{mouseButton:MouseBindings.Primary}]});tg.setToolActive(PanTool.toolName,{bindings:[{mouseButton:MouseBindings.Auxiliary}]});tg.setToolActive(ZoomTool.toolName,{bindings:[{mouseButton:MouseBindings.Secondary}]});tg.setToolActive(StackScrollMouseWheelTool.toolName);state.initialized=true;addEventListener('resize',()=>{state.renderingEngine?.resize(true,true);state.viewport?.render()})}
async function loadFiles(list){const files=[...list].filter(f=>f.size>0);if(!files.length)return;stopCine();loading(true,'Preparando '+files.length+' archivo(s)…');try{await init();const parsed=[];for(let i=0;i<files.length;i++){loading(true,'Leyendo '+(i+1)+' de '+files.length+'…');const f=files[i];parsed.push({file:f,meta:parseBasic(f,await f.arrayBuffer())})}parsed.sort((a,b)=>String(a.meta.seriesInstanceUID||'').localeCompare(String(b.meta.seriesInstanceUID||''))||(a.meta.instanceNumber||0)-(b.meta.instanceNumber||0));state.files=parsed.map(x=>x.file);state.imageMeta=parsed.map(x=>x.meta);state.imageIds=state.files.map(f=>dicomImageLoader.wadouri.fileManager.add(f));state.currentIndex=0;updateStudy();updateList();await displayStack();el.dropOverlay.classList.add('hidden');el.statusText.textContent=files.length+' archivo(s) cargado(s) localmente.'}catch(e){console.error(e);el.statusText.textContent='Error al cargar el estudio.';alert('No se pudo cargar el estudio DICOM. Revisa la consola.')}finally{loading(false)}}
async function displayStack(){if(!state.viewport||!state.imageIds.length)return;await state.viewport.setStack(state.imageIds,state.currentIndex);state.viewport.render();state.originalVOI=state.viewport.getProperties().voiRange||null;updateSlice();updateViewport()}
function updateStudy(){const m=state.imageMeta[0]||{};el.patientName.textContent=m.patientName||'—';el.patientId.textContent=m.patientId||'—';el.studyDescription.textContent=m.studyDescription||m.seriesDescription||'—';el.modality.textContent=m.modality||'—';el.studyDate.textContent=m.studyDate||'—';el.hudPatient.textContent='PACIENTE '+(m.patientName||'—');el.hudStudy.textContent='ESTUDIO '+(m.studyDescription||m.seriesDescription||'—');el.hudModality.textContent=m.modality||'—'}
function updateList(){el.seriesList.innerHTML='';el.imageCountBadge.textContent=state.imageIds.length;state.imageMeta.forEach((m,i)=>{const n=document.createElement('div');n.className='series-item '+(i===state.currentIndex?'active':'');n.innerHTML='<div class="thumb">'+String(i+1).padStart(2,'0')+'</div><div><div class="series-name">'+esc(m.seriesDescription||m.fileName)+'</div><div class="series-sub">Imagen '+(i+1)+' · '+esc(m.modality||'DICOM')+'</div></div>';n.onclick=()=>setSlice(i);el.seriesList.appendChild(n)})}
function updateSlice(){const total=state.imageIds.length;el.sliceSlider.max=Math.max(0,total-1);el.sliceSlider.value=state.currentIndex;el.sliceSlider.disabled=total<=1;el.sliceLabel.textContent=(total?state.currentIndex+1:0)+' / '+total;el.hudSlice.textContent=(total?state.currentIndex+1:0)+' / '+total;el.prevBtn.disabled=state.currentIndex<=0;el.nextBtn.disabled=state.currentIndex>=total-1;[...el.seriesList.children].forEach((n,i)=>n.classList.toggle('active',i===state.currentIndex));const m=state.imageMeta[state.currentIndex];el.fileInfo.textContent=m?m.fileName:'Sin estudio cargado'}
function updateViewport(){if(!state.viewport)return;const p=state.viewport.getProperties(),v=p.voiRange;if(v)el.windowText.textContent=Math.round(v.upper-v.lower)+' / '+Math.round((v.upper+v.lower)/2);const z=state.viewport.getZoom?.();if(typeof z==='number')el.zoomText.textContent=z.toFixed(2)+'×'}
async function setSlice(i){if(!state.imageIds.length)return;state.currentIndex=Math.max(0,Math.min(i,state.imageIds.length-1));await state.viewport.setImageIdIndex(state.currentIndex);state.viewport.render();updateSlice();updateViewport()}
function reset(){if(!state.viewport)return;state.viewport.resetCamera();if(state.originalVOI)state.viewport.setProperties({voiRange:state.originalVOI});state.viewport.setProperties({invert:false});state.viewport.render();updateViewport()}
function invert(){if(!state.viewport)return;state.viewport.setProperties({invert:!state.viewport.getProperties().invert});state.viewport.render()}
function zoom(f){if(!state.viewport)return;state.viewport.setZoom((state.viewport.getZoom?.()||1)*f);state.viewport.render();updateViewport()}
function fit(){if(!state.viewport)return;state.viewport.resetCamera({resetPan:false,resetZoom:true,resetToCenter:true});state.viewport.render();updateViewport()}
function fullscreen(){document.fullscreenElement?document.exitFullscreen():el.viewport.requestFullscreen?.()}
function stopCine(){state.cinePlaying=false;if(state.cineTimer)clearInterval(state.cineTimer);state.cineTimer=null;el.cineBtn.innerHTML='▶<span>Cine</span>'}
function cine(){if(state.cinePlaying){stopCine();return}if(state.imageIds.length<2)return;state.cinePlaying=true;el.cineBtn.innerHTML='■<span>Detener</span>';state.cineTimer=setInterval(()=>setSlice((state.currentIndex+1)%state.imageIds.length),90)}
el.openFilesBtn.onclick=()=>el.fileInput.click();el.openFolderBtn.onclick=()=>el.folderInput.click();el.fileInput.onchange=e=>loadFiles(e.target.files);el.folderInput.onchange=e=>loadFiles(e.target.files);el.sliceSlider.oninput=e=>setSlice(+e.target.value);el.prevBtn.onclick=()=>setSlice(state.currentIndex-1);el.nextBtn.onclick=()=>setSlice(state.currentIndex+1);el.cineBtn.onclick=cine;
document.querySelectorAll('.toolbar button[data-action]').forEach(b=>b.onclick=()=>({reset,invert,zoomIn:()=>zoom(1.2),zoomOut:()=>zoom(1/1.2),fit,fullscreen,cine}[b.dataset.action])());
document.onkeydown=e=>{if(e.key==='ArrowLeft')setSlice(state.currentIndex-1);if(e.key==='ArrowRight')setSlice(state.currentIndex+1);if(e.key.toLowerCase()==='r')reset();if(e.key.toLowerCase()==='i')invert();if(e.key.toLowerCase()==='f')fullscreen();if(e.code==='Space'){e.preventDefault();cine()}};
['dragenter','dragover'].forEach(t=>el.viewport.addEventListener(t,e=>{e.preventDefault();el.dropOverlay.classList.remove('hidden')}));el.viewport.addEventListener('drop',e=>{e.preventDefault();loadFiles(e.dataTransfer.files)});init().catch(e=>{console.error(e);el.statusText.textContent='No se pudo inicializar el visor.'});